#!/bin/bash

# Build the Docker image
echo "Building continuum Docker image..."
docker build -t continuum .

echo ""
echo "=========================================================="
echo "To run the full FastAPI backend service locally:"
echo "=========================================================="
echo "docker run -it -p 8000:8000 \\"
echo "  -e LLM_BASE_URL=\"https://api.fireworks.ai/inference/v1\" \\"
echo "  -e LLM_API_KEY=\"your_fireworks_api_key_here\" \\"
echo "  -e LLM_MODEL=\"accounts/fireworks/models/deepseek-v4-pro\" \\"
echo "  -e VISION_LLM_BASE_URL=\"https://api.fireworks.ai/inference/v1\" \\"
echo "  -e VISION_LLM_API_KEY=\"your_fireworks_api_key_here\" \\"
echo "  -e VISION_LLM_MODEL=\"accounts/fireworks/models/kimi-k2p6\" \\"
echo "  -e AWS_REGION=\"us-east-1\" \\"
echo "  -e AWS_S3_BUCKET_NAME=\"continuum-ai\" \\"
echo "  -e AWS_ACCESS_KEY_ID=\"\" \\"
echo "  -e AWS_SECRET_ACCESS_KEY=\"\" \\"
echo "  -e CLERK_ISSUER=\"\" \\"
echo "  continuum"
echo ""
echo "=========================================================="
echo "Or, to run the CLI pipeline directly on a local video:"
echo "=========================================================="
echo "docker run -it \\"
echo "  -e LLM_API_KEY=\"your_fireworks_api_key_here\" \\"
echo "  -e VISION_LLM_API_KEY=\"your_fireworks_api_key_here\" \\"
echo "  -v \$(pwd)/scenes:/app/scenes \\"
echo "  -v \$(pwd)/output:/app/output \\"
echo "  continuum python3 main.py --input-video scenes/source_film.mp4 --output-dir output"
